spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://139.224.83.90:3306/base_crud?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用DruidSource数据源
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源连接配置相关
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时时间
    maxWait: 60000
    # 配置检测间隔时间，检测会关闭空闲连接，单位时是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在连接池中最小存活时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否为有效SQL，必须为一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
    testOnBorrow: false
    # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
    testOnReturn: false
    # 是否缓存preparedStatement,mysql5.5+建议开启
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # jpa相关的配置
  jpa:
    hibernate:
      # 更新或创建数据表结构
      ddl-auto: update
    # 控制台显示SQL
    show-sql: true

server:
  port: 9090
  servlet:
    context-path: /jpa
